config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'application#index'
  get 'signin', to: 'sessions#index'
  get 'signup', to: 'users#new'

  post 'message', to: 'application#create_message'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  mount ActionCable.server, at: '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  validates :body, presence: true

  belongs_to :user

  scope :custom_display, -> { order(:created_at).last(20) }
end

app/models/user.rb
class User < ApplicationRecord
  validates :username,
      presence: true,
      length: { minimum: 3, maximum: 24 },
      uniqueness: { case_sensitive: false }

  has_many :messages
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :require_user, only: [:index]
  helper_method :current_user, :logged_in?

  def index
    @message = Message.new
    @messages = Message.custom_display
  end

  def create_message
    @message = Message.new body: params[:message][:body], user: current_user
    if @message.save
      ActionCable.server.broadcast "chatroom_channel", mod_message: message_render(@message)
    end
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:error] = "You must be logged in to perform that action"
      redirect_to signin_path
    end
  end

  def message_render(message)
    render(partial: 'messages/message', locals: {message: message})
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  before_action :logged_in_redirect, only: [:index, :create]
  skip_before_action :require_user, only: [:index, :create]

  def index
  end

  def create
    user = User.find_by(username: params[:session][:username])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "You have successfully logged in"
      redirect_to root_path
    else
      flash[:error] = "There was something wrong with your login information"
      redirect_to signin_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "You have successfully logged out"
    redirect_to signin_path
  end

  private
  def logged_in_redirect
    if logged_in?
      flash[:error] = "You are already logged in"
      redirect_to root_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/index.html.erb
<h4 class="ui center aligned icon header">
  <i class="circular orange coffee icon"></i>
  Say Something on MessageMe, <em><%= current_user.username %></em>
</h4>
<div class="ui two column grid">
  <div class="twelve wide column">
    <div class="ui fluid raised card chatbox">
      <div class="content">
        <div class="ui small feed" id="message-container">
          <%= render @messages %>
        </div>
      </div>
      <div class="extra content">
        <%= form_for(@message, html: {class: "ui reply form", role: "form"}, url: message_path, remote: true) do |f| %>
          <div class="field">
            <div class="ui fluid icon input ">
              <%= f.text_field :body, placeholder: "Enter a message", id: 'message-input' %>
              <%# <input type="text" placeholder="Enter a message..."> %>
              <%= f.button '<i class="bordered inverted orange edit icon"></i>'.html_safe %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>

  <div class="four wide column">
    <div class="ui fluid raised card chatbox">
      <div class="content">
        <div class="ui inverted vertical menu">
          <a class="active item">
            Home
          </a>
          <a class="item">
            Messages
          </a>
          <a class="item">
            Friends
          </a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<div class="ui small inverted menu">
  <div class="ui container">
    <%= link_to "Chatroom", root_path, class: 'item' %>
    <a class="item">
      Messages
    </a>
    <div class="right menu">
      <div class="ui dropdown item">
        Account <i class="dropdown icon"></i>
        <div class="menu">
          <% if logged_in? %>
            <%= link_to "Log out", logout_path, class: 'item', method: :delete %>
          <% else %>
            <%= link_to "Log in", signin_path, class: 'item' %>
          <% end %>
        </div>
      </div>
      <% if !logged_in? %>
        <div class="item">
          <%= link_to "Log in", signin_path, class: 'ui primary button' %>
       </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do | message_type, message_content | %>
  <div class="ui <%= message_type %> message transition">
    <i class="close icon"></i>
    <div class="header">
      <%= message_content %>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MessageMe</title>
    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="ui container">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="event">
  <div class="content">
    <div class="summary">
      <a>
        <em>
          <% if message.user == current_user %>
            <span style="color: red;">Myself</span>
          <% else %>
            <%= message.user.username%>
          <% end %>
        </em>
      </a>: <%= message.body %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<h2>new user</h2>